"""add chunk_size and chunk_overlap to rag_config

Revision ID: 7b5c507741f9
Revises: 8745a0e998b8
Create Date: 2026-07-05 03:30:04.353759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5c507741f9'
down_revision: Union[str, Sequence[str], None] = '8745a0e998b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_config', sa.Column('chunk_size', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('rag_config', sa.Column('chunk_overlap', sa.Integer(), nullable=False, server_default='200'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_config', 'chunk_overlap')
    op.drop_column('rag_config', 'chunk_size')
    # ### end Alembic commands ###
