"""added is_active field in config class

Revision ID: 7d887d6ff539
Revises: 7f3b3a02ddc3
Create Date: 2026-04-08 20:23:21.680579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d887d6ff539'
down_revision: Union[str, Sequence[str], None] = '7f3b3a02ddc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_config', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_config', 'is_active')
    # ### end Alembic commands ###
