"""removed chunk_size and overlap config class 

Revision ID: 7f3b3a02ddc3
Revises: b24c0f5809f6
Create Date: 2026-04-08 20:05:16.677264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3b3a02ddc3'
down_revision: Union[str, Sequence[str], None] = 'b24c0f5809f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_config', 'chunk_size')
    op.drop_column('rag_config', 'chunk_overlap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_config', sa.Column('chunk_overlap', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rag_config', sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
