"""created config class

Revision ID: b24c0f5809f6
Revises: 73e56b6a0479
Create Date: 2026-04-08 18:55:56.654211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24c0f5809f6'
down_revision: Union[str, Sequence[str], None] = '73e56b6a0479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('search_category', sa.Enum('Hybrid', 'Semantic', 'Keyword', name='searchcategory'), nullable=False),
    sa.Column('reranker', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('chunk_overlap < chunk_size', name='check_chunk_overlap_less_than_chunk_size'),
    sa.CheckConstraint('chunk_overlap >= 0', name='check_chunk_overlap_non_negative'),
    sa.CheckConstraint('chunk_size <= 2048', name='check_chunk_size_max'),
    sa.CheckConstraint('chunk_size > 0', name='check_chunk_size_positive'),
    sa.CheckConstraint('temperature <= 1.0', name='check_temperature_max'),
    sa.CheckConstraint('temperature >= 0.0', name='check_temperature_non_negative'),
    sa.CheckConstraint('top_k > 0', name='check_top_k_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_config')
    # ### end Alembic commands ###
